import type { ProductListItem, ProductDetail, PriceHistoryEntry } from "./types";

export const MOCK_PRODUCTS: ProductListItem[] = [
  {
    id: "1",
    brand: "Dior",
    name: "Sauvage Eau de Parfum",
    size_ml: 100,
    gender: "men",
    image_url: null,
    cheapest_price: 89.9,
    cheapest_site: "primor",
  },
  {
    id: "2",
    brand: "Chanel",
    name: "Coco Mademoiselle",
    size_ml: 50,
    gender: "women",
    image_url: null,
    cheapest_price: 99.0,
    cheapest_site: "nocibe",
  },
  {
    id: "3",
    brand: "Yves Saint Laurent",
    name: "Black Opium",
    size_ml: 90,
    gender: "women",
    image_url: null,
    cheapest_price: 74.5,
    cheapest_site: "sephora",
  },
  {
    id: "4",
    brand: "Giorgio Armani",
    name: "Acqua di Gio",
    size_ml: 100,
    gender: "men",
    image_url: null,
    cheapest_price: 68.0,
    cheapest_site: "primor",
  },
  {
    id: "5",
    brand: "Lancôme",
    name: "La Vie Est Belle",
    size_ml: 75,
    gender: "women",
    image_url: null,
    cheapest_price: 82.0,
    cheapest_site: "nocibe",
  },
  {
    id: "6",
    brand: "Hermès",
    name: "Terre d'Hermès",
    size_ml: 100,
    gender: "men",
    image_url: null,
    cheapest_price: 115.0,
    cheapest_site: "sephora",
  },
];

export const MOCK_PRODUCT_DETAIL: ProductDetail = {
  id: "1",
  brand: "Dior",
  name: "Sauvage Eau de Parfum",
  size_ml: 100,
  gender: "men",
  image_url: null,
  listings: [
    {
      id: "l1",
      site: "primor",
      url: "https://fr.primor.eu/dior-sauvage-100ml",
      name_on_site: "Dior Sauvage EDP 100ml",
      image_url: null,
      latest_price: 89.9,
      in_stock: true,
      last_seen_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    },
    {
      id: "l2",
      site: "sephora",
      url: "https://www.sephora.fr/p/dior-sauvage-100ml",
      name_on_site: "Sauvage - Eau de Parfum",
      image_url: null,
      latest_price: 95.0,
      in_stock: true,
      last_seen_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    },
    {
      id: "l3",
      site: "nocibe",
      url: "https://www.nocibe.fr/dior-sauvage-100ml",
      name_on_site: "DIOR Sauvage EDP 100ml",
      image_url: null,
      latest_price: 92.5,
      in_stock: false,
      last_seen_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    },
  ],
};

export const MOCK_HISTORY: PriceHistoryEntry[] = [
  { listing_id: "l1", site: "primor", price: 95.0, in_stock: true, scraped_at: "2026-04-01T10:00:00Z" },
  { listing_id: "l2", site: "sephora", price: 98.0, in_stock: true, scraped_at: "2026-04-01T10:00:00Z" },
  { listing_id: "l3", site: "nocibe", price: 97.0, in_stock: true, scraped_at: "2026-04-01T10:00:00Z" },
  { listing_id: "l1", site: "primor", price: 92.0, in_stock: true, scraped_at: "2026-04-15T10:00:00Z" },
  { listing_id: "l2", site: "sephora", price: 95.0, in_stock: true, scraped_at: "2026-04-15T10:00:00Z" },
  { listing_id: "l3", site: "nocibe", price: 94.0, in_stock: true, scraped_at: "2026-04-15T10:00:00Z" },
  { listing_id: "l1", site: "primor", price: 89.9, in_stock: true, scraped_at: "2026-05-01T10:00:00Z" },
  { listing_id: "l2", site: "sephora", price: 95.0, in_stock: true, scraped_at: "2026-05-01T10:00:00Z" },
  { listing_id: "l3", site: "nocibe", price: 92.5, in_stock: false, scraped_at: "2026-05-01T10:00:00Z" },
];
